#!/bin/bash
#
# Copyright 2013, The Sporting Exchange Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


LOG_FILE=`dirname $0`
LOG_FILE=${LOG_FILE}/wget.log

EXPECTS_FILE=`dirname $0`
EXPECTS_FILE=${EXPECTS_FILE}/wget.expects

if [[ -f $EXPECTS_FILE ]]; then

  SIZE=`du $EXPECTS_FILE | awk '{printf("%s\n",$1);}'`
  if [[ $SIZE = 0 ]]; then
    echo "ERROR: Unexpected call to wget with arguments: $*" >> $LOG_FILE
    exit 1
  fi

  EXPECT=`cat $EXPECTS_FILE | head -1`
  cat $EXPECTS_FILE | tail --lines=+2 > 1
  mv 1 $EXPECTS_FILE

  if [[ "$EXPECT" != "$*" ]]; then
    echo "ERROR: Invalid call to wget, expected [$EXPECT], got [$*]" >> $LOG_FILE
    exit 1
  fi
fi

COMMANDS_FILE=`dirname $0`
COMMANDS_FILE=${COMMANDS_FILE}/wget.commands

if [[ ! -f $COMMANDS_FILE ]]; then
  exit 0
fi

SIZE=`du $COMMANDS_FILE | awk '{printf("%s\n",$1);}'`
if [[ $SIZE = 0 ]]; then
  exit 0
fi

COMMAND=`cat $COMMANDS_FILE | head -1`
cat $COMMANDS_FILE | tail --lines=+2 > 1
mv 1 $COMMANDS_FILE
eval "$COMMAND"
